# Generated by Django 3.2 on 2022-01-04 12:58

import catalogue.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0003_alter_productfavorite_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name': 'جزئیات', 'verbose_name_plural': 'جزیبات محصولات'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'برند', 'verbose_name_plural': 'برند ها'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created',), 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productcolor',
            options={'verbose_name': 'رنگ', 'verbose_name_plural': 'رنگ محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productfavorite',
            options={'ordering': ('-created',), 'verbose_name': 'علاقه مندی', 'verbose_name_plural': 'علاقه مندی ها'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'تصویر محصول', 'verbose_name_plural': 'تصاویر محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productsale',
            options={'verbose_name': 'فروش محصول', 'verbose_name_plural': 'فروش محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'verbose_name': 'سایز محصول', 'verbose_name_plural': 'سایز محصولات'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'نوع محصول', 'verbose_name_plural': 'انواع محصولات'},
        ),
        migrations.AlterModelOptions(
            name='view',
            options={'verbose_name': 'بازدید', 'verbose_name_plural': 'بازدید ها'},
        ),
        migrations.AlterField(
            model_name='attribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalogue.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='title',
            field=models.CharField(max_length=120, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='value',
            field=models.CharField(max_length=240, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='catalogue.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='english_name',
            field=models.CharField(max_length=64, verbose_name='اسم به انگلیسی'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='is_child',
            field=models.BooleanField(default=False, verbose_name='زیر مجموعه است/ نیست'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=64, verbose_name='اسم'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalogue.brand', verbose_name='برند والد'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=64, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='english_name',
            field=models.CharField(max_length=64, verbose_name='اسم به انگیسی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_child',
            field=models.BooleanField(default=False, verbose_name='زیر مجموعه است/ نیست'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64, verbose_name='اسم'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalogue.category', verbose_name='دسته بندی والد'),
        ),
        migrations.AlterField(
            model_name='category',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='catalogue.producttype', verbose_name='نوع محصول'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=64, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalogue.Brand', verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='products', to='catalogue.Category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='english_title',
            field=models.CharField(max_length=120, verbose_name='عنوان انگلیسی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='exist',
            field=models.BooleanField(default=True, verbose_name='وجود دارد/ندارد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیر فعال'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ اخرین تغییرات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalogue.producttype', verbose_name='نوع محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=120, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='special_sale',
            field=models.BooleanField(default=False, verbose_name='فروش ویژه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=120, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='product',
            name='upc',
            field=models.BigIntegerField(verbose_name='شماره اختصاصی'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='color',
            field=models.CharField(choices=[('#2196f3', 'آبی'), ('#f6f6f6', 'سفید'), ('#212121', 'مشکلی'), ('#FF0000', 'قرمز'), ('#FFC0CB', 'صورتی'), ('#FFA500', 'نارنجی'), ('#FFFF00', 'زرد')], max_length=32, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='catalogue.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productfavorite',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='productfavorite',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='catalogue.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/%Y/%m/%d/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalogue.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='catalogue.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(catalogue.models.get_user_sale), related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='catalogue.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='value',
            field=models.PositiveSmallIntegerField(choices=[(1, 'S'), (2, 'M'), (3, 'L'), (4, 'XL'), (5, 'XXL'), (6, 'L-XL')], default=3, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='english_title',
            field=models.CharField(max_length=120, verbose_name='عنوان به انگلیسی'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=120, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='title',
            field=models.CharField(max_length=120, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='view',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='catalogue.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='view',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
