# Generated by Django 3.2 on 2022-01-25 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20220104_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='catalogue.producttype'),
        ),
    ]
