# Generated by Django 3.2 on 2021-12-27 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ناشناس', max_length=64)),
                ('question', models.TextField()),
                ('notify', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_child', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='catalogue.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120)),
                ('positive_point', models.CharField(blank=True, max_length=500, null=True)),
                ('negative_point', models.CharField(blank=True, max_length=500, null=True)),
                ('body', models.TextField()),
                ('suggest', models.PositiveSmallIntegerField(choices=[(1, 'توصیه میکنم'), (2, 'توصیه نمیکنم'), (3, 'نظری ندارم')], default=3)),
                ('quality', models.PositiveSmallIntegerField(choices=[(1, 'خیلی بد'), (2, 'بد'), (3, 'نرمال'), (4, 'خوب'), (5, 'خیلی خوب')], default=3)),
                ('cost', models.PositiveSmallIntegerField(choices=[(1, 'خیلی بد'), (2, 'بد'), (3, 'نرمال'), (4, 'خوب'), (5, 'خیلی خوب')], default=3)),
                ('innovation', models.PositiveSmallIntegerField(choices=[(1, 'خیلی بد'), (2, 'بد'), (3, 'نرمال'), (4, 'خوب'), (5, 'خیلی خوب')], default=3)),
                ('features', models.PositiveSmallIntegerField(choices=[(1, 'خیلی بد'), (2, 'بد'), (3, 'نرمال'), (4, 'خوب'), (5, 'خیلی خوب')], default=3)),
                ('easiness', models.PositiveSmallIntegerField(choices=[(1, 'خیلی بد'), (2, 'بد'), (3, 'نرمال'), (4, 'خوب'), (5, 'خیلی خوب')], default=3)),
                ('designing', models.PositiveSmallIntegerField(choices=[(1, 'خیلی بد'), (2, 'بد'), (3, 'نرمال'), (4, 'خوب'), (5, 'خیلی خوب')], default=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='catalogue.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('modified',),
            },
        ),
    ]
