# Generated by Django 3.2 on 2022-01-04 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20220104_1628'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('modified',), 'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterModelOptions(
            name='productquestion',
            options={'ordering': ('-created',), 'verbose_name': 'سوال', 'verbose_name_plural': 'سوالات'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cost',
            field=models.PositiveSmallIntegerField(choices=[(1, 'خیلی بد'), (2, 'بد'), (3, 'نرمال'), (4, 'خوب'), (5, 'خیلی خوب')], default=3, verbose_name='قسمت'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت نظر'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='designing',
            field=models.PositiveSmallIntegerField(choices=[(1, 'خیلی بد'), (2, 'بد'), (3, 'نرمال'), (4, 'خوب'), (5, 'خیلی خوب')], default=3, verbose_name='طراحی'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='easiness',
            field=models.PositiveSmallIntegerField(choices=[(1, 'خیلی بد'), (2, 'بد'), (3, 'نرمال'), (4, 'خوب'), (5, 'خیلی خوب')], default=3, verbose_name='سهولت در استفاده'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='features',
            field=models.PositiveSmallIntegerField(choices=[(1, 'خیلی بد'), (2, 'بد'), (3, 'نرمال'), (4, 'خوب'), (5, 'خیلی خوب')], default=3, verbose_name='امکانات'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='innovation',
            field=models.PositiveSmallIntegerField(choices=[(1, 'خیلی بد'), (2, 'بد'), (3, 'نرمال'), (4, 'خوب'), (5, 'خیلی خوب')], default=3, verbose_name='نو آوری'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فغال/غیر فعال'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییر نظر'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='negative_point',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='نقاط ضعف'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='positive_point',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='نقاط قوت'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='catalogue.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='quality',
            field=models.PositiveSmallIntegerField(choices=[(1, 'خیلی بد'), (2, 'بد'), (3, 'نرمال'), (4, 'خوب'), (5, 'خیلی خوب')], default=3, verbose_name='کیفیت'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='subject',
            field=models.CharField(max_length=120, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='suggest',
            field=models.PositiveSmallIntegerField(choices=[(1, 'توصیه میکنم'), (2, 'توصیه نمیکنم'), (3, 'نظری ندارم')], default=3, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='productquestion',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='productquestion',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال/ غیر فعال'),
        ),
        migrations.AlterField(
            model_name='productquestion',
            name='is_child',
            field=models.BooleanField(default=False, verbose_name='بازخور'),
        ),
        migrations.AlterField(
            model_name='productquestion',
            name='name',
            field=models.CharField(default='ناشناس', max_length=64, verbose_name='اسم'),
        ),
        migrations.AlterField(
            model_name='productquestion',
            name='notify',
            field=models.BooleanField(default=False, verbose_name='اعلن بازخورد/اعلان ندارد'),
        ),
        migrations.AlterField(
            model_name='productquestion',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='catalogue.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productquestion',
            name='question',
            field=models.TextField(verbose_name='سوال'),
        ),
        migrations.AlterField(
            model_name='productquestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
