# Generated by Django 3.2 on 2022-01-04 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('id',), 'verbose_name': 'آدرس', 'verbose_name_plural': 'آدرس ها'},
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=32, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='address',
            name='fullname',
            field=models.CharField(max_length=64, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیر فعال'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(max_length=18, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_address',
            field=models.TextField(max_length=500, verbose_name='آدرس دقیق'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=32, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(max_length=32, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
